# Generated by Django 5.2 on 2025-05-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_shopper_username_alter_shopper_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopper',
            name='username',
        ),
        migrations.AlterField(
            model_name='shopper',
            name='email',
            field=models.EmailField(max_length=240, unique=True),
        ),
    ]
