# Generated by Django 5.2 on 2025-05-03 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_remove_shopper_username_alter_shopper_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shopper',
            managers=[
            ],
        ),
    ]
