# Generated by Django 5.2 on 2025-04-14 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_rename_product_image_product_product_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pruduct_description',
            new_name='product_description',
        ),
    ]
