# Generated by Django 5.2 on 2025-04-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_rename_pruduct_description_product_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
