# Generated by Django 5.2 on 2025-04-19 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dashboard', '0003_rename_pruduct_description_product_product_description'),
        ('Home', '0002_remove_product_product_categorie_delete_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.product')),
            ],
        ),
    ]
