# Generated by Django 5.2 on 2025-05-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_cart_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
